{
 "title": "Stock Prediction API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"stock-predictions-api\"}[$__rate_interval])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"stock-predictions-api\"}[$__rate_interval])",
     "legendFormat": "CPU Seconds"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"stock-predictions-api\"}[$__rate_interval])",
     "legendFormat": "{{handler}}-{{status}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"stock-predictions-api\"}",
     "legendFormat": "Memory Bytes"
    }
   ]
  }
 ]
}